# Generated by Django 4.2.5 on 2024-01-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi')], max_length=25)),
                ('duration', models.DurationField(default='00:00')),
                ('dateofrelease', models.DateField()),
                ('poster_url', models.URLField(help_text='Enter the URL Movie Poster', null=True)),
            ],
        ),
    ]
