# Generated by Django 4.2.5 on 2024-02-04 14:31

import User.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NowShowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=25)),
                ('duration', models.DurationField(default='HH:MM:SS')),
                ('poster_url', models.URLField(help_text='Enter the URL Movie Poster')),
                ('showTimes', models.JSONField(max_length=50)),
                ('showbegins', models.DateField()),
                ('showends', models.DateField()),
                ('date_of_release', models.DateField()),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=25)),
                ('booking_id', models.CharField(default=User.models.Ticket.generate_booking_id, max_length=150, unique=True)),
                ('seat_number', models.JSONField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=200, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='User.nowshowing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
