# Generated by Django 4.2.5 on 2024-02-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='name',
        ),
        migrations.AddField(
            model_name='show',
            name='upcoming',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
