# Generated by Django 4.2.5 on 2024-01-24 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_showtime_date_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime_date',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='showdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.showtime_date'),
        ),
    ]
