# Generated by Django 4.2.5 on 2024-01-24 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_showtime_date_movie_movie_showdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime_date',
            name='show_end_date',
        ),
        migrations.RemoveField(
            model_name='showtime_date',
            name='show_start_date',
        ),
        migrations.AddField(
            model_name='showtime_date',
            name='show_date',
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='showdetails',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.showtime_date'),
        ),
    ]
