# Generated by Django 4.2.5 on 2024-01-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_showtime_date_show_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='dateofrelease',
            new_name='date_of_release',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='showdetails',
            new_name='show_details',
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(default='hh:mm'),
        ),
    ]
