# Generated by Django 4.2.5 on 2024-01-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_dateofrelease_movie_date_of_release_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.CharField(choices=[('11:30 AM', '11:30 AM'), ('02:30 PM', '02:30 PM'), ('05:00 PM', '05:00 PM'), ('09:00 PM', '09:00 PM')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='show_details',
        ),
        migrations.DeleteModel(
            name='ShowTime_Date',
        ),
        migrations.AddField(
            model_name='movie',
            name='show_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.showdate'),
        ),
        migrations.AddField(
            model_name='movie',
            name='show_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.showtime'),
        ),
    ]
