# Generated by Django 4.2.5 on 2024-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_showdate_showtime_remove_movie_show_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='show_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='show_time',
            field=models.CharField(choices=[('11:30 AM', '11:30 AM'), ('02:30 PM', '02:30 PM'), ('05:00 PM', '05:00 PM'), ('09:00 PM', '09:00 PM')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='ShowDate',
        ),
        migrations.DeleteModel(
            name='ShowTime',
        ),
    ]
