# Generated by Django 4.2.5 on 2024-01-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_movie_show_date_alter_movie_show_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('11:30 AM', '11:30 AM'), ('02:30 PM', '02:30 PM'), ('05:00 PM', '05:00 PM'), ('09:00 PM', '09:00 PM')], max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='show_time',
        ),
        migrations.AddField(
            model_name='movie',
            name='available_dates',
            field=models.ManyToManyField(blank=True, related_name='movies', to='User.availabledate'),
        ),
        migrations.AddField(
            model_name='movie',
            name='show_times',
            field=models.ManyToManyField(blank=True, related_name='movies', to='User.showtime'),
        ),
    ]
