# Generated by Django 4.2.5 on 2024-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_availabledate_showtime_remove_movie_show_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='available_dates',
            field=models.ManyToManyField(blank=True, to='User.availabledate'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='show_times',
            field=models.ManyToManyField(blank=True, to='User.showtime'),
        ),
    ]
