# Generated by Django 4.2.5 on 2024-01-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_movie_available_dates_alter_movie_show_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='available_dates',
            field=models.ManyToManyField(null=True, to='User.availabledate'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='show_times',
            field=models.ManyToManyField(null=True, to='User.showtime'),
        ),
    ]
