# Generated by Django 4.2.5 on 2024-01-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_movie_available_dates_alter_movie_show_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.CharField(choices=[('11:30 AM', '11:30 AM'), ('02:30 PM', '02:30 PM'), ('05:00 PM', '05:00 PM'), ('09:00 PM', '09:00 PM')], max_length=15)),
                ('show_date', models.DateField(null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='available_dates',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='show_times',
        ),
        migrations.DeleteModel(
            name='AvailableDate',
        ),
        migrations.DeleteModel(
            name='ShowTime',
        ),
        migrations.AddField(
            model_name='movie',
            name='show_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.showtime_date'),
        ),
    ]
