# Generated by Django 4.2.5 on 2024-01-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_showtime_date_remove_movie_available_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='show_details',
        ),
        migrations.AddField(
            model_name='movie',
            name='show_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='show_time',
            field=models.CharField(choices=[('11:30 AM', '11:30 AM'), ('02:30 PM', '02:30 PM'), ('05:00 PM', '05:00 PM'), ('09:00 PM', '09:00 PM')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ShowTime_Date',
        ),
    ]
