# Generated by Django 4.2.5 on 2024-01-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_remove_movie_show_details_movie_show_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='show_date',
            new_name='availableDates',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='show_time',
            new_name='showTimes',
        ),
    ]
