# Generated by Django 4.2.5 on 2024-01-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_rename_show_date_movie_availabledates_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_seats', models.JSONField(default=list)),
                ('movie_price', models.FloatField(default=10.0)),
            ],
        ),
    ]
