# Generated by Django 4.2.5 on 2024-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_seatdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='movie',
            name='showTimes',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
