# Generated by Django 4.2.5 on 2024-01-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_movie_genre_alter_movie_showtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='availableDates',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_of_release',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
