# Generated by Django 4.2.5 on 2024-01-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_alter_movie_availabledates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='date_of_release',
        ),
    ]
