# Generated by Django 4.2.5 on 2024-01-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_remove_movie_date_of_release'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatData',
        ),
    ]
