# Generated by Django 4.2.5 on 2024-01-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_delete_seatdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='availableDates',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='showTimes',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_of_release',
            field=models.DateField(null=True),
        ),
    ]
