# Generated by Django 4.2.5 on 2024-01-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_remove_movie_availabledates_remove_movie_showtimes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
    ]
