# Generated by Django 4.2.5 on 2024-01-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_remove_movie_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_of_release',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
