# Generated by Django 4.2.5 on 2024-01-27 15:53

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_alter_movie_date_of_release_alter_movie_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(default=timezone.timedelta(hours=2)),
        ),
    ]
