# Generated by Django 4.2.5 on 2024-01-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_of_release',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
