# Generated by Django 4.2.5 on 2024-01-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_alter_movie_date_of_release_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_of_release',
            field=models.DateField(null=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
