# Generated by Django 4.2.5 on 2024-01-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_alter_movie_date_of_release_alter_movie_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='availableDates',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(help_text='Enter the URL Movie Poster', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='showTimes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date_of_release',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(max_length=150),
        ),
    ]
