# Generated by Django 4.2.5 on 2024-01-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_movie_availabledates_movie_poster_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NowShowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=25)),
                ('duration', models.DurationField()),
                ('poster_url', models.URLField(help_text='Enter the URL Movie Poster', null=True)),
                ('showTimes', models.CharField(max_length=50, null=True)),
                ('availableDates', models.DateField(null=True)),
                ('date_of_release', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
