# Generated by Django 4.2.5 on 2024-01-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_nowshowing_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowing',
            name='availableDates',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nowshowing',
            name='date_of_release',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nowshowing',
            name='duration',
            field=models.DurationField(default='HH:MM:SS'),
        ),
        migrations.AlterField(
            model_name='nowshowing',
            name='poster_url',
            field=models.URLField(help_text='Enter the URL Movie Poster'),
        ),
        migrations.AlterField(
            model_name='nowshowing',
            name='showTimes',
            field=models.JSONField(max_length=50),
        ),
    ]
