# Generated by Django 4.2.5 on 2024-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_alter_nowshowing_availabledates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowing',
            name='showTimes',
            field=models.JSONField(default=list, max_length=50),
        ),
    ]
