# Generated by Django 4.2.5 on 2024-01-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_alter_nowshowing_showtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowing',
            name='showTimes',
            field=models.JSONField(max_length=50),
        ),
    ]
