# Generated by Django 4.2.5 on 2024-01-29 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_alter_nowshowing_showtimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nowshowing',
            old_name='availableDates',
            new_name='showbegins',
        ),
        migrations.AddField(
            model_name='nowshowing',
            name='showends',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
