# Generated by Django 4.2.5 on 2024-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_rename_availabledates_nowshowing_showbegins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nowshowing',
            name='showends',
            field=models.DateField(),
        ),
    ]
